### ISSUE TITLE
Missing captions reported. 

### ISSUE THREAD

**Issue by thriveweb** [thriveweb/photoswipe-masonry-v2#1]

**Comment by thriveweb** [comment]
Only on full size

**Comment by vstokstad** [comment]
Yes, since latest update all captions are gone on full-size images! This is quite a huge problem for us. Is there a way to go back? Or can you make a fix ASAP?

**Comment by thriveweb** [comment]
Updated now :)

**Comment by vstokstad** [comment]
Thank you! Great plugin!

**Comment by vstokstad** [comment]
Is there a way to make the caption-section wider? so that a longer text don't impact image size as much?

**Comment by thriveweb** [comment]
Can you post a link so I can see the issue? It should be possible with some CSS.
