### ISSUE TITLE
Request: Compatibility with Enhanced Media Library

### ISSUE THREAD

**Issue by thriveweb** [thriveweb/photoswipe-masonry-v2#12]
https://wordpress.org/support/topic/compatibility-with-enhanced-media-library-2/

**Comment by Jon007** [comment]
Suspect this should be closed, the change commented in this thread is already in the code...
I've been using Enhanced Media Library for a year and I'm actually not sure what the issue even was...

**Comment by thriveweb** [comment]
Thanks :)
