### ISSUE TITLE
photoswipe ui buttons mouse-over shows zoom for all buttons

### ISSUE THREAD

**Issue by Jon007** [thriveweb/photoswipe-masonry-v2#19]
on mouseover of any of the buttons at the top right, they all change to the show the zoom icon, they should just show change background colour without losing the action icon.

**Comment by thriveweb** [comment]
This seems to be a conflict with some themes such as Twenty Seventeen.

There is a generic style 

```

button:hover {
    background: #767676;
}

```

Causing the issue on hover. I'm not having much luck clearing the style...

**Comment by Jon007** [comment]
I don't think it's that, the icon is specifically changing on hover to show the photoswipe zoom icon...
Also doesn't happen I notice on your wooswipe demo http://kilim.co/shop/harena/#&gid=1&pid=2

**Comment by Jon007** [comment]
Got this, the images are set by using a background offset into the .svg, and this is being cleared on hover.

To fix, this include :hover on the selectors that use this in the skin.css and default-skin.css, e.g.:

.pswp__button--close, .pswp__button--close:hover {
  background-position: 0 -44px; }

.pswp__button--share, .pswp__button--share:hover {
  background-position: -44px -44px; }

.pswp__button--fs {
  display: none; }

.pswp--supports-fs .pswp__button--fs {
  display: block; }

.pswp--fs .pswp__button--fs, .pswp--fs .pswp__button--fs:hover {
  background-position: -44px 0; }

.pswp__button--zoom, .pswp__button--zoom:hover {
  display: none;
  background-position: -88px 0; }

.pswp--zoom-allowed .pswp__button--zoom {
  display: block; }

.pswp--zoomed-in .pswp__button--zoom, .pswp--zoomed-in .pswp__button--zoom:hover {
  background-position: -132px 0; }



On 2 Jan 2017, at 15:09, Dean Oakley <notifications@github.com <mailto:notifications@github.com>> wrote:

This seems to be a conflict with some themes such as Twenty Seventeen.

There is a generic style


button:hover {
    background: #767676;
}

Causing the issue on hover. I'm not having much luck clearing the style...

**Comment by Jon007** [comment]
of course this is Dmitry's code so fixes should be fed back to him to get fixed in the master...

**Comment by thriveweb** [comment]
Good one, that works 👍 

I don't there is an issue with Dmitry's code. Themes shouldn't have these broad css rules.

**Comment by Jon007** [comment]
The :hover that changes the background colour is in Dimitry's code,
The themes aren't changing the background position, that appears to be a side effect, being reset when the background colour is reset


On 3 Jan 2017, at 00:09, Dean Oakley <notifications@github.com> wrote:

Good one, that works 👍

I don't there is an issue with Dmitry's code. Themes shouldn't have these broad css rules.

**Comment by thriveweb** [comment]
The button:hover in the theme was overriding the background-position. It wasn't happening on all themes.
