### ISSUE TITLE
New Settings page issues

### ISSUE THREAD

**Issue by Jon007** [thriveweb/photoswipe-masonry-v2#31]
Hi,
on the new settings page:

1. First install gives:
" Notice: Undefined index: crop_thumbnails in ..wp-content/plugins/photoswipe-masonry/backend/settings-view.php on line 74
/>
Crop thumbnails"

1. wording/phrasing around Thumbnail width is unclear:
Thumbnail Width
Set the width of the grid thumbnails
Thumbnail Height
Set the height of the grid thumbnails
Is that setting max width and max height or min width and height, or absolute values?   or is it absolute values if "Crop thumbnails" is also set.

1. if there is further work going into the plugin it may be preferable to remove ALL of the settings on this page and instead allow attributes on the gallery shortcode.  Or as a secondary choice, keep the attributes but allow them to be overridden in the gallery shortcode.

1. 3 spelling errors in the sentence:

> We reccomand you to regenerate your thumbnails te get te best result.

1. it's best to add a Settings link from the plugins.php listing to the settings page

**Comment by thriveweb** [comment]
Thanks, we will look into these. There is still a bit todo...

**Comment by thriveweb** [comment]
Thanks again Jon. Feel free to get in there and make changes! 

1.  is fixed. 
2. Just updated
3. Agreed. 
4. Is fixed
