### ISSUE TITLE
Current master branch shows 2 copies of gallery

### ISSUE THREAD

**Issue by Jon007** [thriveweb/photoswipe-masonry-v2#32]
On current master branch there is an extra gallery copy appearing at the top of the screen (output directly after body).
(tested eg with vanilla twenty-sixteen theme)

**Comment by thriveweb** [comment]
Thanks for testing. We'll have a look this week.

**Comment by thriveweb** [comment]
Hmm, not seeing this.

**Comment by Jon007** [comment]
maybe it's fixed by now...  close then
