### ISSUE TITLE
Sharing and link to image broken in version 1.2.1

### ISSUE THREAD

**Issue by underbjerg** [thriveweb/photoswipe-masonry-v2#4]
Hi,

After the upgrade to version 1.2.1, linking directly to an image with ex. #&gid=1&pid=13 no longer works. It did work earlier (version 1.1.2 I think).

As a consequence, sharing from the lightbox (e.g. via Facebook) is also broken, since the link generated (with gid and pid) doesn’t point towards the image being shared.

It is also broken on the plugin homepage, for example:
http://thriveweb.com.au/the-lab/photoswipe/#&gid=1&pid=13

I wanted to downgrade to plugin version 1.1.2, but everything before version 1.2.0 seems to have been removed from SVN and Git, so now I’m stuck with a non-working version :-(

Please help, either by fixing the latest version, or by making version 1.1.2 available for downgrading.

**Comment by thriveweb** [comment]
Yes this looks broken. I don't think it worked in 1.2.0 either. 

See the old versions here https://github.com/thriveweb/photoswipe-masonry/releases

I'll fix in the next update!

**Comment by thriveweb** [comment]
Here is 1.1.2

[photoswipe-masonry-1.1.0.zip](https://github.com/thriveweb/photoswipe-masonry/files/299555/photoswipe-masonry-1.1.0.zip)

**Comment by thriveweb** [comment]
Here is 1.1.2

[photoswipe-masonry.zip](https://github.com/thriveweb/photoswipe-masonry/files/299556/photoswipe-masonry.zip)

**Comment by underbjerg** [comment]
Perfect, thank you! I downgraded to 1.1.2, and it works again.

Looking forward to the next version - I'm loving this plugin :)

**Comment by thriveweb** [comment]
The should be fixed in the latest version.
