### ISSUE TITLE
Photo always open in a new page

### ISSUE THREAD

**Issue by allampatu** [thriveweb/photoswipe-masonry-v2#8]
Hello Dev,
when I click on the thumbnail, first open the lightbox and then it open full url image.

I've set up the gallery with no url image but it seems not affect the gallery.

In console, there aren't js errors.

Can you help to figure out?

Thanks

**Comment by thriveweb** [comment]
Hi, can you please post a link to demo this issue. 

There may be a conflict if your theme has a built in gallery. See if you can disable it.

**Comment by allampatu** [comment]
Nevermind, I removed the plugin.
thanks anyway
